apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trendstore
  template:
    metadata:
      labels:
        app: trendstore
    spec:
      containers:
      - name: trendstore
        image: vijayguptacloud/trendstore-app:v1
        ports:
        - containerPort: 80
